### ISSUE TITLE
ERROR: vlsi-core.jar not exists 

### ISSUE THREAD

**Issue by hackereye** [vmware-serengeti/serengeti-ws#4]
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-install-plugin:2.4:install-file (install-vsli-core) on project vlsiLibrary: The specified file '/home/fuh/git-repo/serengeti-ws/lib/vlsi/vlsi-core.jar' not exists -> [Help 1]

**Comment by caitsithx** [comment]
You need download the official vsphere client jars from vmware.com and put them inside serengeti-ws/lib/vlsi.
